--Checking for data_type of each column
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH,
       IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MHDashboard'; -- Replace with your table name

-- Sample data for testing 
INSERT INTO MHDashboard(Patient_ID, Reason_for_Assessment, Sex, Marital_Status, Language, Education, Employment, Employment_Insurance, Pension, Social_Assistance, Disability_Insurance, Other, Amount_of_Time_Hospitalized, Contact_with_Community_Mental_Health, assessment__date, Number_of_Psychiatric_Admissions_Recent, Number_of_Psychiatric_Admissions_Lifetime, Time_Since_Last_Discharge, Addiction_Counsellor, Alcohol_drug_treatment_smoking_cessation, Date_of_Birth, Age_at_First_Hospitalization, Psychologist_or_Psychometrist)
VALUES
(1, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'FEMALE', 'MARRIED', 'ENGLISH', 'HIGH SCHOOL', 'YES', 'YES', 'NO', 'YES', 'NO', 'NO', '30 DAYS OR LESS', '30 DAYS OR LESS', 6-7-2018, 'NONE', '6 OR MORE', 'NOT APPLICABLE', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 24-12-1958, '65+', '0 DAYS'),
(2, 'INITIAL ASSESSMENT', 'MALE', 'MARRIED', 'FRENCH', 'HIGH SCHOOL', 'YES', 'YES', 'YES', 'YES', 'NO', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', 'NO CONTACT IN LAST YEAR', 17-9-2018, 'NONE', 'NONE', 'NOT APPLICABLE', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 15-11-1981, '65+', '3 DAYS'),
(3, 'INITIAL ASSESSMENT', 'MALE', 'NEVER MARRIED', 'POLISH', 'HIGH SCHOOL', 'NO', 'YES', 'YES', 'NO', 'NO', 'NO', '', 'NO CONTACT IN LAST YEAR', 18-7-2018, '1 to 2', 'NONE', '31 DAYS TO 1 YEAR', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 15-11-1981, '65+', '0 DAYS'),
(4, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'MALE', 'MARRIED', 'MANDARIN CHINESE', 'BACHELORS DEGREE', 'NO', 'NO', 'YES', 'YES', 'NO', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', '30 DAYS OR LESS', 13-9-2018, 'NONE', 'NONE', 'NOT APPLICABLE', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 22-12-1976, '65+', '0 DAYS'),
(5, 'INITIAL ASSESSMENT', 'MALE', 'MARRIED', 'ENGLISH', 'UNKNOWN', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', '30 DAYS OR LESS', '31 DAYS OR MORE', 26-8-2017, '3 OR MORE', '4 to 5', '31 DAYS TO 1 YEAR', '3 DAYS', 'NO INTERVENTION OF THIS TYPE', 17-11-1968, '65+', '7 DAYS'),
(6, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'FEMALE', 'NEVER MARRIED', 'ITALIAN', 'SOME COLLEGE/UNIVERSITY', 'NO', 'NO', 'YES', 'NO', '', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', 'NO CONTACT IN LAST YEAR', 18-8-2017, '1 to 2', '4 to 5', '31 DAYS TO 1 YEAR', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 18-2-1982, '65+', '1 DAY'),
(7, 'INITIAL ASSESSMENT', 'MALE', 'MARRIED', 'OTHER', 'HIGH SCHOOL', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', '30 DAYS OR LESS', 1-9-2017, '1 to 2', '6 OR MORE', '31 DAYS TO 1 YEAR', '', 'NO INTERVENTION OF THIS TYPE', 4-8-1929, '65+', '1 DAY'),
(8, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'MALE', 'NEVER MARRIED', 'ENGLISH', 'HIGH SCHOOL', 'NO', 'YES', 'YES', 'NO', 'NO', 'NO', '30 DAYS OR LESS', '30 DAYS OR LESS', 8-8-2017, '3 OR MORE', '1 to 2', 'NOT APPLICABLE', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 20-5-1976, '65+', '0 DAYS'),
(9, 'INITIAL ASSESSMENT', 'MALE', 'NEVER MARRIED', 'SPANISH', '9-11 GRADES', 'NO', 'YES', 'YES', 'YES', 'NO', 'YES', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', 'NO CONTACT IN LAST YEAR', 29-7-2017, '3 OR MORE', '1 to 2', 'MORE THAN 1 YEAR', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 1-8-1982, '25-44', '2 DAYS'),
(10, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'FEMALE', 'MARRIED', 'POLISH', 'BACHELORS DEGREE', 'NO', 'YES', 'YES', 'NO', 'NO', 'NO', '31 DAYS TO 1 YEAR', 'NO CONTACT IN LAST YEAR', 25-5-2017, '3 OR MORE', '1 to 2', '30 DAYS OR LESS (FROM OTHER FACILITY)', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 10-11-1943, '25-44', '0 DAYS'),
(11, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'FEMALE', 'NEVER MARRIED', 'KOREAN', 'SOME COLLEGE/UNIVERSITY', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', '30 DAYS OR LESS', 11-08-2017, '1 to 2', '4 to 5', 'MORE THAN 1 YEAR', '4 DAYS', 'NO INTERVENTION OF THIS TYPE', 17-10-1964, '45-64', '0 DAYS'),
(12, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'FEMALE', 'NEVER MARRIED', 'CANTONESE', 'HIGH SCHOOL', 'NO', 'NO', 'YES', 'YES', 'YES', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', '31 DAYS OR MORE', 5-8-2017, '3 OR MORE', '1 to 2', '31 DAYS TO 1 YEAR', '1 DAY', 'NO INTERVENTION OF THIS TYPE', 21-12-1978, '25-44', '0 DAYS'),
(13, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'MALE', 'NEVER MARRIED', 'PORTUGUESE', 'HIGH SCHOOL', 'NO', 'NO', 'YES', 'YES', 'NO', 'YES', '30 DAYS OR LESS', '30 DAYS OR LESS', 28-7-2017, 'NONE', '4 to 5', '31 DAYS TO 1 YEAR', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 6-9-1990, '15-24', '0 DAYS'),
(14, 'INITIAL ASSESSMENT', 'MALE', 'NEVER MARRIED', 'FRENCH', '9-11 GRADES', 'NO', 'NO', 'YES', 'YES', 'NO', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', 'NO CONTACT IN LAST YEAR', 7-9-2017, '1 to 2', '1 to 2', 'NOT APPLICABLE', '2 DAYS', 'RECEIVED IN LAST 7 DAYS', 22-6-1988, '15-24', '0 DAYS'),
(15, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'FEMALE', 'NEVER MARRIED', 'PORTUGUESE', 'GRADUATE DEGREE', 'YES', 'NO', 'YES', 'NO', 'NO', 'NO', '30 DAYS OR LESS', '30 DAYS OR LESS', 17-8-2017, 'NONE', 'NONE', 'MORE THAN 1 YEAR', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 14-3-1943, '15-24', '7 DAYS'),
(16, 'INITIAL ASSESSMENT', 'MALE', 'MARRIED', 'RUSSIAN', 'GRADUATE DEGREE', 'YES', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', '30 DAYS OR LESS', 4-6-2017, '1 to 2', 'NONE', '30 DAYS OR LESS (FROM OTHER FACILITY)', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 14-03-2018, '15-24', '0 DAYS'),
(17, 'INITIAL ASSESSMENT', 'FEMALE', 'DIVORCED', 'KOREAN', 'HIGH SCHOOL', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', '30 DAYS OR LESS', 'NO CONTACT IN LAST YEAR', 6-7-2017, 'NONE', 'NONE', 'NOT APPLICABLE', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 7-9-1975, '25-44', '0 DAYS'),
(18, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'FEMALE', 'NEVER MARRIED', 'OTHER', 'BACHELORS DEGREE', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', '30 DAYS OR LESS', 'NO CONTACT IN LAST YEAR', 5-7-2017, 'NONE', '4 to 5', '31 DAYS TO 1 YEAR', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 28-9-1979, '25-44', '0 DAYS'),
(19, 'INITIAL ASSESSMENT', 'FEMALE', 'NEVER MARRIED', 'CANTONESE', 'BACHELORS DEGREE', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', 'NO CONTACT IN LAST YEAR', 27-7-2017, 'NONE', 'NONE', 'NOT APPLICABLE', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 9-2-1937, '25-44', '5 DAYS'),
(20, 'INITIAL ASSESSMENT', 'MALE', 'MARRIED', 'ITALIAN', 'BACHELORS DEGREE', 'YES', 'YES', 'NO', 'NO', 'NO', 'NO', '30 DAYS OR LESS', 'NO CONTACT IN LAST YEAR', 07-07-2003, '3 OR MORE', 'NONE', 'MORE THAN 1 YEAR', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 30-4-1940, '25-44', '0 DAYS'),
(21, 'INITIAL ASSESSMENT', 'FEMALE', 'NEVER MARRIED', 'HEBREW', 'BACHELORS DEGREE', 'YES', 'NO', 'YES', 'YES', 'YES', 'NO', '31 DAYS TO 1 YEAR', '30 DAYS OR LESS', 2-9-2017, 'NONE', '6 OR MORE', 'NOT APPLICABLE', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 24-12-1976, '15-24', '0 DAYS'),
(22, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'FEMALE', 'MARRIED', 'SPANISH', 'HIGH SCHOOL', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', '30 DAYS OR LESS', 11-08-2018, '3 OR MORE', '6 OR MORE', '31 DAYS TO 1 YEAR', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 1-8-1942, '15-24', '0 DAYS'),
(23, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'MALE', 'MARRIED', 'BULGARIAN', 'SOME COLLEGE/UNIVERSITY', 'NO', 'NO', 'YES', 'YES', 'NO', 'NO', '30 DAYS OR LESS', '31 DAYS OR MORE', 31-5-2018, '3 OR MORE', '6 OR MORE', '30 DAYS OR LESS (FROM THIS FACILITY)', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 25-5-1991, '15-24', '0 DAYS'),
(24, 'INITIAL ASSESSMENT', 'FEMALE', 'NEVER MARRIED', 'RUSSIAN', '9-11 GRADES', 'YES', 'YES', 'YES', 'YES', 'NO', 'NO', 'NO OTHER ADMISSIONS IN LAST 2 YEARS', '30 DAYS OR LESS', 16-6-2017, 'NONE', 'NONE', 'NOT APPLICABLE', '0 DAYS', 'NO INTERVENTION OF THIS TYPE', 24-5-1993, '15-24', '2 DAYS'),
(25, 'REVIEW PRIOR TO DISCHARGE FROM PROGRAM', 'FEMALE', 'DIVORCED', 'HEBREW', 'HIGH SCHOOL', 'YES', 'NO', 'NO', 'YES', 'NO', 'NO', '30 DAYS OR LESS', '30 DAYS OR LESS', 19-6-2017, 'NONE', '', '31 DAYS TO 1 YEAR', '0 DAYS', 'RECEIVED IN LAST 7 DAYS', 5-6-1937, '15-24', '0 DAYS');

-- Verify the new data in the MHDashboard table
SELECT *
FROM MHDashboard
Where Patient_ID>0 AND Patient_ID<26;

-- Check for null values we added as sample in the MHDashboard table
SELECT *
FROM MHDashboard
WHERE Patient_ID IS NULL OR LTRIM(RTRIM(Patient_ID)) = ''
	OR Reason_for_Assessment IS NULL OR LTRIM(RTRIM(Reason_for_Assessment)) = ''
	OR Sex IS NULL OR LTRIM(RTRIM(Sex)) = ''
	OR Marital_Status IS NULL OR LTRIM(RTRIM(Marital_Status)) = ''
	OR Language IS NULL OR LTRIM(RTRIM(Language)) = ''
	OR Education IS NULL OR LTRIM(RTRIM(Education)) = ''
	OR Employment IS NULL OR LTRIM(RTRIM(Employment)) = ''
	OR Employment_Insurance IS NULL OR LTRIM(RTRIM(Employment_Insurance)) = ''
	OR Pension IS NULL OR LTRIM(RTRIM(Pension)) = ''
	OR Social_Assistance IS NULL OR LTRIM(RTRIM(Social_Assistance)) = ''
	OR Disability_Insurance IS NULL OR LTRIM(RTRIM(Disability_Insurance)) = ''
	OR Other IS NULL OR LTRIM(RTRIM(Other)) = ''
	OR Amount_of_Time_Hospitalized IS NULL OR LTRIM(RTRIM(Amount_of_Time_Hospitalized)) = ''
	OR Contact_with_Community_Mental_Health IS NULL OR LTRIM(RTRIM(Contact_with_Community_Mental_Health)) = ''
	OR assessment__date IS NULL OR LTRIM(RTRIM(assessment__Date)) = ''
	OR Number_of_Psychiatric_Admissions_Recent IS NULL OR LTRIM(RTRIM(Number_of_Psychiatric_Admissions_Recent)) = ''
	OR Number_of_Psychiatric_Admissions_Lifetime IS NULL OR LTRIM(RTRIM(Number_of_Psychiatric_Admissions_Lifetime)) = ''
	OR Time_Since_Last_Discharge IS NULL OR LTRIM(RTRIM(Time_Since_Last_Discharge)) = ''
	OR Addiction_Counsellor IS NULL OR LTRIM(RTRIM(Addiction_Counsellor)) = ''
	OR Alcohol_drug_treatment_smoking_cessation IS NULL OR LTRIM(RTRIM(Alcohol_drug_treatment_smoking_cessation)) = ''
	OR Date_of_Birth IS NULL OR LTRIM(RTRIM(Date_of_Birth)) = ''
	OR Age_at_First_Hospitalization IS NULL OR LTRIM(RTRIM(Age_at_First_Hospitalization)) = ''
	OR Psychologist_or_Psychometrist IS NULL OR LTRIM(RTRIM(Psychologist_or_Psychometrist)) = '';

--Dropping sample data from MHDatabase Table
DELETE FROM MHDashboard
WHERE Patient_ID>0 and Patient_ID<26;